server:
  error:
    include-binding-errors: always
    include-message: always

# modificar secret y configurar el que corresponda

feature:
  toggle:
    apiUrl: http://localhost:4242/api
    appName: app-name-default
    clientSecret: "default:development.1ee5fb49a9f0f124853a2deee73a2da98d0ee36846ea400eff06e1fc"
    instanceId: "1"
    service: "fakeFeatureFlag" # unleash